runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3


#[START gae_flex_mysql_env]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:password@/emotions?unix_socket=/cloudsql/quick-elixir-425417-d0:australia-southeast1:gsqltaha-11
#[END gae_flex_mysql_env]

#[START gae_flex_mysql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: quick-elixir-425417-d0:australia-southeast1:gsqltaha-11
#[END gae_flex_mysql_settings]